import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surfaceApp,
  },
  feedbackOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  feedbackCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: colors.white,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 22,
    alignItems: 'center',
    shadowColor: colors.textPrimary,
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 30,
    elevation: 10,
  },
  feedbackIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  feedbackIconWrapSuccess: {
    backgroundColor: colors.primaryStrong,
  },
  feedbackIconWrapError: {
    backgroundColor: colors.dangerSurfaceStrong,
  },
  feedbackTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
  },
  feedbackMessage: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  feedbackButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackButtonSuccess: {
    backgroundColor: colors.primaryStrong,
  },
  feedbackButtonError: {
    backgroundColor: colors.danger,
  },
  feedbackButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
  },
  confirmCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: colors.white,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 22,
    alignItems: 'center',
    shadowColor: colors.textPrimary,
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 30,
    elevation: 10,
  },
  confirmIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  confirmTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
  },
  confirmMessage: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  confirmActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  confirmCancelButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  confirmCancelButtonText: {
    color: colors.textBody,
    fontSize: 17,
    fontWeight: '700',
  },
  confirmDeleteButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.danger,
  },
  confirmDeleteButtonDisabled: {
    opacity: 0.85,
  },
  confirmDeleteButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
  },
  successOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    backgroundColor: colors.white,
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 22,
    alignItems: 'center',
    shadowColor: colors.textPrimary,
    shadowOpacity: 0.18,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 30,
    elevation: 10,
  },
  successIconWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.dangerSurfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  successIconInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 10,
  },
  successMessage: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
  },
  successButton: {
    width: '100%',
    minHeight: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.danger,
  },
  successButtonText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  headerSpacer: {
    width: 42,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    paddingHorizontal: 20,
    paddingBottom: 36,
  },
  heroSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 22,
  },
  heroImageWrap: {
    width: 122,
    height: 122,
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: colors.successSurfaceAlt,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    marginRight: 18,
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: {
    flex: 1,
  },
  assetName: {
    fontSize: 21,
    lineHeight: 28,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 10,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  assetTypeBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  assetTypeBadgeText: {
    fontSize: 14,
    color: colors.textBody,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.successBorderStrong,
    backgroundColor: colors.white,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  editButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  heroNotes: {
    marginTop: 12,
    fontSize: 14,
    lineHeight: 20,
    color: colors.textTertiary,
  },
  assetReference: {
    marginTop: 10,
    fontSize: 12,
    color: colors.textTertiary,
  },
  statusCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 3,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: 72,
  },
  statusIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusIconGreen: {
    backgroundColor: colors.successSoft,
  },
  statusIconRed: {
    backgroundColor: colors.dangerSurface,
  },
  statusCopy: {
    flex: 1,
    justifyContent: 'center',
  },
  statusTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 4,
    
  },
  statusSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textTertiary,
  },
  statusControl: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
  },
  statusStateText: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
  },
  statusStateTextOn: {
    color: colors.primaryStrong,
  },
  statusStateTextOff: {
    color: colors.textTertiary,
  },
  statusStateTextDanger: {
    color: colors.danger,
  },
  divider: {
    height: 1,
    backgroundColor: colors.surfaceCool,
    marginVertical: 16,
  },
  statusDivider: {
    height: 1,
    backgroundColor: colors.surfaceCool,
    marginVertical: 10,
  },
  activityCard: {
    marginTop: 16,
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 22,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 25,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  activityIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityCopy: {
    flex: 1,
  },
  activityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  activityTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  lastBadge: {
    borderRadius: 999,
    backgroundColor: colors.successSurfaceBright,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  lastBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryStrong,
  },
  activityMeta: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textTertiary,
  },
  emptyActivityWrap: {
    paddingTop: 14,
    paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyActivityText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textMuted,
    textAlign: 'center',
  },
  emptyActivityHint: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textTertiary,
  },
  deleteButton: {
    marginTop: 18,
    borderRadius: 18,
    backgroundColor: colors.dangerCritical,
    paddingHorizontal: 18,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: colors.dangerDark,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 4,
  },
  deleteButtonDisabled: {
    opacity: 0.8,
  },
  deleteIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: colors.overlayWhite14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  deleteCopy: {
    flex: 1,
  },
  deleteTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.white,
    marginBottom: 4,
  },
  deleteSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.overlayWhite92,
  },
});
