import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  header: {
    minHeight: 60,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.white,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.textStrong,
  },
  headerSpacer: {
    width: 40,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 34,
    gap: 18,
  },
  formSection: {
    gap: 10,
  },
  formSectionRaised: {
    zIndex: 30,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fieldLabelIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.successSurface,
  },
  fieldLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textBody,
  },
  fieldWrap: {
    position: 'relative',
  },
  textField: {
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    fontSize: 15,
    color: colors.textPrimary,
  },
  textFieldWithCounter: {
    paddingRight: 64,
  },
  textFieldError: {
    borderColor: colors.dangerStrong,
  },
  selectField: {
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.white,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectWrap: {
    position: 'relative',
    zIndex: 20,
  },
  selectPlaceholder: {
    fontSize: 15,
    color: colors.textMuted,
  },
  selectValue: {
    fontSize: 15,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  categoryModalRoot: {
    flex: 1,
  },
  categoryModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
  },
  categoryDropdownCard: {
    position: 'absolute',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.white,
    overflow: 'hidden',
    shadowColor: colors.textPrimary,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 24,
    elevation: 5,
  },
  categoryDropdownScroll: {
    flexGrow: 0,
  },
  textAreaWrap: {
    position: 'relative',
  },
  textAreaWrapWithCounter: {
    minHeight: 138,
  },
  textArea: {
    minHeight: 138,
    paddingTop: 14,
    paddingBottom: 36,
  },
  counterText: {
    position: 'absolute',
    right: 16,
    bottom: 14,
    fontSize: 12,
    color: colors.textMuted,
  },
  fieldCounterText: {
    position: 'absolute',
    right: 16,
    bottom: 10,
    fontSize: 12,
    color: colors.textMuted,
  },
  imageUploadCard: {
    minHeight: 160,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    backgroundColor: colors.successSurfaceTint,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  imagePreviewCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    backgroundColor: colors.successSurfaceTint,
    overflow: 'hidden',
  },
  previewImageLarge: {
    width: '100%',
    height: 220,
    backgroundColor: colors.surfaceApp,
  },
  changeImageRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.white,
  },
  changeImageText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primaryBase,
  },
  imageUploadIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.successSurface,
    marginBottom: 14,
    position: 'relative',
  },
  imageUploadPlusBadge: {
    position: 'absolute',
    right: 2,
    bottom: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryBase,
  },
  imageUploadTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primaryBase,
    textAlign: 'center',
    marginBottom: 4,
  },
  imageUploadHint: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
  },
  errorText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.dangerStrong,
    marginTop: -2,
  },
  submitBtn: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: colors.primaryBase,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    shadowColor: colors.primaryBase,
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 4,
  },
  submitBtnDisabled: {
    opacity: 0.7,
  },
  submitBtnText: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '700',
  },
  cancelButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  cancelButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.primaryBase,
  },
  categoryOption: {
    minHeight: 56,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryOptionSelected: {
    backgroundColor: colors.primaryBase,
  },
  categoryOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  categoryOptionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.successSurface,
  },
  categoryOptionIconWrapSelected: {
    backgroundColor: colors.overlayWhite22,
  },
  categoryOptionText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textStrong,
  },
  categoryOptionTextSelected: {
    color: colors.white,
  },
  categoryOptionDivider: {
    height: 1,
    backgroundColor: colors.surfaceCoolSoft,
    marginLeft: 16,
  },
});
