import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.white,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 112,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  headerTextWrap: {
    flex: 1,
    paddingRight: 16,
  },
  welcomeText: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  subtitleText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.textTertiary,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    minHeight: 138,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 16,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    justifyContent: 'space-between',
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 4,
  },
  totalCard: {
    backgroundColor: colors.accentSoft,
  },
  activeCard: {
    backgroundColor: colors.white,
  },
  inactiveCard: {
    backgroundColor: colors.warningSurfaceSoft,
  },
  statIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderWidth: 1,
  },
  totalIconContainer: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  activeIconContainer: {
    borderColor: colors.successSoftStrong,
  },
  inactiveIconContainer: {
    borderColor: colors.warningBorder,
  },
  statNumber: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 16,
  },
  statLabel: {
    fontSize: 14,
    color: colors.textTertiary,
    fontWeight: '500',
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  messageCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  messageText: {
    fontSize: 14,
    color: colors.textTertiary,
  },
  errorCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    padding: 20,
    shadowColor: colors.dangerShadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 2,
  },
  errorTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.dangerDeep,
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.dangerDark,
  },
  retryButton: {
    alignSelf: 'flex-start',
    marginTop: 16,
    borderRadius: 999,
    backgroundColor: colors.primaryStrong,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  emptyStateCard: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 0,
    paddingVertical: 8,
    alignItems: 'center',
  },
  emptyIllustration: {
    width: '100%',
    height: 196,
    borderRadius: 24,
    backgroundColor: colors.white,
    marginBottom: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  emptyIllustrationImage: {
    width: '100%',
    height: '100%',
  },
  floatingIconBubble: {
    position: 'absolute',
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.successSoftStrong,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 3,
  },
  leftBubble: {
    left: 24,
    top: 46,
  },
  rightBubble: {
    right: 24,
    top: 58,
  },
  qrBadge: {
    width: 88,
    height: 88,
    borderRadius: 28,
    backgroundColor: colors.primaryStrong,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primaryShadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    elevation: 6,
  },
  emptyTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 13,
    lineHeight: 19,
    color: colors.textMuted,
    textAlign: 'center',
    alignSelf: 'center',
    maxWidth: 380,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  emptyHint: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.textTertiary,
    textAlign: 'center',
    marginTop: 2,
  },
  assetList: {
    gap: 14,
  },
  assetCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: 16,
    shadowColor: colors.textPrimary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 3,
  },
  assetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  assetImageWrap: {
    width: 82,
    height: 62,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.surfaceApp,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  assetImage: {
    width: '100%',
    height: '100%',
  },
  assetImageFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetIconActive: {
    backgroundColor: colors.successSoft,
  },
  assetIconInactive: {
    backgroundColor: colors.warningSurface,
  },
  assetInfo: {
    flex: 1,
  },
  assetName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 3,
  },
  assetMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  assetMetaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    backgroundColor: colors.accentSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  assetMeta: {
    fontSize: 11,
    color: colors.accentText,
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  assetActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginLeft: 12,
    flexShrink: 0,
    alignSelf: 'center',
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusBadgeActive: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
  },
  statusBadgeInactive: {
    backgroundColor: colors.warningSurface,
    borderColor: colors.warningBorder,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  statusBadgeTextActive: {
    color: colors.primaryText,
  },
  statusBadgeTextInactive: {
    color: colors.warningStrong,
  },
  assetChevron: {
    marginLeft: 2,
  },
  assetQuickResponseText: {
    fontSize: 12,
    color: colors.textTertiary,
    marginTop: 10,
  },
});

